// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for footer documents
 */
interface FooterDocumentData {
  /**
   * About field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.about
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about: prismic.RichTextField;

  /**
   * Contact box field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contact_box
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_box: prismic.RichTextField;

  /**
   * Address box field in *footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address_box
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address_box: prismic.RichTextField;

  /**
   * image field in *footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | ProjectShowcaseSliceSlice
  | FrontpageHeroSliceSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Page settings documents
 */
interface PageSettingsDocumentData {
  /**
   * favicon field in *Page settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_settings.favicon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  favicon: prismic.ImageField<never>;

  /**
   * page title field in *Page settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_settings.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * page image field in *Page settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_settings.page_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  page_image: prismic.ImageField<never>;

  /**
   * page description field in *Page settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optimal SEO description length is 150-160 characters
   * - **API ID Path**: page_settings.page_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_description: prismic.KeyTextField;

  /**
   * about text field in *Page settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_settings.about_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about_text: prismic.RichTextField;

  /**
   * Contact box field in *Page settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_settings.contact_box
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_box: prismic.RichTextField;
}

/**
 * Page settings document from Prismic
 *
 * - **API ID**: `page_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PageSettingsDocumentData>,
    "page_settings",
    Lang
  >;

type ProjectDocumentDataSlicesSlice =
  | ProjectVideoSectionSliceSlice
  | DescriptionSliceSlice
  | ProjectImageSectionSlice;

/**
 * Content for project documents
 */
interface ProjectDocumentData {
  /**
   * title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * featured image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *project*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: project.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice>; /**
   * seo title field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.seo_title
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_title: prismic.KeyTextField;

  /**
   * seo description field in *project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optimal SEO description length is 150-160 characters
   * - **API ID Path**: project.seo_description
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seo_description: prismic.KeyTextField;

  /**
   * seo image field in *project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.seo_image
   * - **Tab**: seo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  seo_image: prismic.ImageField<never>;
}

/**
 * project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HomepageDocument
  | PageSettingsDocument
  | ProjectDocument;

/**
 * Primary content in *DescriptionSlice → Default → Primary*
 */
export interface DescriptionSliceSliceDefaultPrimary {
  /**
   * text field in *DescriptionSlice → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_slice.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * small text field in *DescriptionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: description_slice.default.primary.small_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  small_text: prismic.KeyTextField;
}

/**
 * Default variation for DescriptionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DescriptionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DescriptionSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DescriptionSlice*
 */
type DescriptionSliceSliceVariation = DescriptionSliceSliceDefault;

/**
 * DescriptionSlice Shared Slice
 *
 * - **API ID**: `description_slice`
 * - **Description**: DescriptionSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DescriptionSliceSlice = prismic.SharedSlice<
  "description_slice",
  DescriptionSliceSliceVariation
>;

/**
 * Item in *FrontpageHeroSlice → Default → Primary → slides*
 */
export interface FrontpageHeroSliceSliceDefaultPrimarySlidesItem {
  /**
   * image field in *FrontpageHeroSlice → Default → Primary → slides*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage_hero_slice.default.primary.slides[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *FrontpageHeroSlice → Default → Primary*
 */
export interface FrontpageHeroSliceSliceDefaultPrimary {
  /**
   * slides field in *FrontpageHeroSlice → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: frontpage_hero_slice.default.primary.slides[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  slides: prismic.GroupField<
    Simplify<FrontpageHeroSliceSliceDefaultPrimarySlidesItem>
  >;
}

/**
 * Default variation for FrontpageHeroSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FrontpageHeroSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FrontpageHeroSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FrontpageHeroSlice*
 */
type FrontpageHeroSliceSliceVariation = FrontpageHeroSliceSliceDefault;

/**
 * FrontpageHeroSlice Shared Slice
 *
 * - **API ID**: `frontpage_hero_slice`
 * - **Description**: FrontpageHeroSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FrontpageHeroSliceSlice = prismic.SharedSlice<
  "frontpage_hero_slice",
  FrontpageHeroSliceSliceVariation
>;

/**
 * Primary content in *ProjectBannerSlice → Default → Primary*
 */
export interface ProjectBannerSliceDefaultPrimary {
  /**
   * image field in *ProjectBannerSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ProjectBannerSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectBannerSlice*
 */
type ProjectBannerSliceVariation = ProjectBannerSliceDefault;

/**
 * ProjectBannerSlice Shared Slice
 *
 * - **API ID**: `project_banner`
 * - **Description**: ProjectBanner
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectBannerSlice = prismic.SharedSlice<
  "project_banner",
  ProjectBannerSliceVariation
>;

/**
 * Primary content in *ProjectImageSectionSlice → Default → Primary*
 */
export interface ProjectImageSectionSliceDefaultPrimary {
  /**
   * help field in *ProjectImageSectionSlice → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Accepts 1 or 2 images. If 2 are added, make sure they have same dimensions!!
   * - **API ID Path**: project_image_section.default.primary.help
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  help: prismic.KeyTextField;

  /**
   * first image field in *ProjectImageSectionSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_section.default.primary.first_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  first_image: prismic.ImageField<never>;

  /**
   * second image field in *ProjectImageSectionSlice → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project_image_section.default.primary.second_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  second_image: prismic.ImageField<never>;

  /**
   * remove container field in *ProjectImageSectionSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project_image_section.default.primary.remove_container
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  remove_container: prismic.BooleanField;
}

/**
 * Default variation for ProjectImageSectionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectImageSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectImageSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectImageSectionSlice*
 */
type ProjectImageSectionSliceVariation = ProjectImageSectionSliceDefault;

/**
 * ProjectImageSectionSlice Shared Slice
 *
 * - **API ID**: `project_image_section`
 * - **Description**: ProjectImageSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectImageSectionSlice = prismic.SharedSlice<
  "project_image_section",
  ProjectImageSectionSliceVariation
>;

/**
 * Primary content in *ProjectShowcaseSlice → Items*
 */
export interface ProjectShowcaseSliceSliceDefaultItem {
  /**
   * showcase field in *ProjectShowcaseSlice → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project_showcase_slice.items[].showcase
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  showcase: prismic.ContentRelationshipField<"project">;
}

/**
 * Default variation for ProjectShowcaseSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ProjectShowcaseSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ProjectShowcaseSlice*
 */
type ProjectShowcaseSliceSliceVariation = ProjectShowcaseSliceSliceDefault;

/**
 * ProjectShowcaseSlice Shared Slice
 *
 * - **API ID**: `project_showcase_slice`
 * - **Description**: ProjectShowcaseSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectShowcaseSliceSlice = prismic.SharedSlice<
  "project_showcase_slice",
  ProjectShowcaseSliceSliceVariation
>;

/**
 * Primary content in *ProjectVideoSectionSlice → Default → Primary*
 */
export interface ProjectVideoSectionSliceSliceDefaultPrimary {
  /**
   * video field in *ProjectVideoSectionSlice → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: project_video_section_slice.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * remove container field in *ProjectVideoSectionSlice → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project_video_section_slice.default.primary.remove_container
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  remove_container: prismic.BooleanField;
}

/**
 * Default variation for ProjectVideoSectionSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectVideoSectionSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProjectVideoSectionSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProjectVideoSectionSlice*
 */
type ProjectVideoSectionSliceSliceVariation =
  ProjectVideoSectionSliceSliceDefault;

/**
 * ProjectVideoSectionSlice Shared Slice
 *
 * - **API ID**: `project_video_section_slice`
 * - **Description**: ProjectVideoSectionSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectVideoSectionSliceSlice = prismic.SharedSlice<
  "project_video_section_slice",
  ProjectVideoSectionSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageSettingsDocument,
      PageSettingsDocumentData,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataSlicesSlice,
      AllDocumentTypes,
      DescriptionSliceSlice,
      DescriptionSliceSliceDefaultPrimary,
      DescriptionSliceSliceVariation,
      DescriptionSliceSliceDefault,
      FrontpageHeroSliceSlice,
      FrontpageHeroSliceSliceDefaultPrimarySlidesItem,
      FrontpageHeroSliceSliceDefaultPrimary,
      FrontpageHeroSliceSliceVariation,
      FrontpageHeroSliceSliceDefault,
      ProjectBannerSlice,
      ProjectBannerSliceDefaultPrimary,
      ProjectBannerSliceVariation,
      ProjectBannerSliceDefault,
      ProjectImageSectionSlice,
      ProjectImageSectionSliceDefaultPrimary,
      ProjectImageSectionSliceVariation,
      ProjectImageSectionSliceDefault,
      ProjectShowcaseSliceSlice,
      ProjectShowcaseSliceSliceDefaultItem,
      ProjectShowcaseSliceSliceVariation,
      ProjectShowcaseSliceSliceDefault,
      ProjectVideoSectionSliceSlice,
      ProjectVideoSectionSliceSliceDefaultPrimary,
      ProjectVideoSectionSliceSliceVariation,
      ProjectVideoSectionSliceSliceDefault,
    };
  }
}
