// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  description_slice: dynamic(() => import('./DescriptionSlice')),
  frontpage_hero_slice: dynamic(() => import('./FrontpageHeroSlice')),
  project_banner: dynamic(() => import('./ProjectBannerSlice')),
  project_image_section: dynamic(() => import('./ProjectImageSectionSlice')),
  project_showcase_slice: dynamic(() => import('./ProjectShowcaseSlice')),
  project_video_section_slice: dynamic(
    () => import('./ProjectVideoSectionSlice')
  ),
}
